216840957,17530664
225333652,38961788
245827540,33531401
226766963,31973182
Traceback (most recent call last):
  File "run.py", line 102, in <module>
    run(exec_map[(algo,gpuflag)]+ " ./datasets/{}.in ./queries/edge-update-queries/queries_{}/{}_queries ./output/{} {}".format(dataset, batch, dataset, outfile, numthread), shell=True, check=True)
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command './exec/CPU/deu ./datasets/slashdot.in ./queries/edge-update-queries/queries_10/slashdot_queries ./output/p64_q10_cpu_dynedge_slashdot.txt 64' died with <Signals.SIGTERM: 15>.
Traceback (most recent call last):
  File "run.py", line 102, in <module>
    run(exec_map[(algo,gpuflag)]+ " ./datasets/{}.in ./queries/edge-update-queries/queries_{}/{}_queries ./output/{} {}".format(dataset, batch, dataset, outfile, numthread), shell=True, check=True)
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command './exec/CPU/deu ./datasets/slashdot.in ./queries/edge-update-queries/queries_40/slashdot_queries ./output/p64_q40_cpu_dynedge_slashdot.txt 64' died with <Signals.SIGTERM: 15>.
Traceback (most recent call last):
  File "run.py", line 102, in <module>
    run(exec_map[(algo,gpuflag)]+ " ./datasets/{}.in ./queries/edge-update-queries/queries_{}/{}_queries ./output/{} {}".format(dataset, batch, dataset, outfile, numthread), shell=True, check=True)
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command './exec/CPU/deu ./datasets/slashdot.in ./queries/edge-update-queries/queries_100/slashdot_queries ./output/p64_q100_cpu_dynedge_slashdot.txt 64' died with <Signals.SIGTERM: 15>.
