11694983,151557
11678989,146359
11690774,126010
11646034,158572
11600390,GPUassert: an illegal memory access was encountered ./src/GPU/dynamic-edge-update.cu 810
Traceback (most recent call last):
  File "run.py", line 102, in <module>
    run(exec_map[(algo,gpuflag)]+ " ./datasets/{}.in ./queries/edge-update-queries/queries_{}/{}_queries ./output/{} {}".format(dataset, batch, dataset, outfile, numthread), shell=True, check=True)
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command './exec/GPU/deu ./datasets/web-webbase-2001.in ./queries/edge-update-queries/queries_100000/web-webbase-2001_queries ./output/p64_q100000_gpu_dynedge_web-webbase-2001.txt ['32']' returned non-zero exit status 188.
